/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSkillsRouteImport } from './routes/_app.skills'
import { Route as AppServicesRouteImport } from './routes/_app.services'
import { Route as AppRunbooksRouteImport } from './routes/_app.runbooks'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppKnowledgeBaseRouteImport } from './routes/_app.knowledge-base'
import { Route as AppIncidentHistoryRouteImport } from './routes/_app.incident-history'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as AppRunbooksIndexRouteImport } from './routes/_app.runbooks.index'
import { Route as AppKnowledgeBaseIndexRouteImport } from './routes/_app.knowledge-base.index'
import { Route as AppInboxIndexRouteImport } from './routes/_app.inbox.index'
import { Route as AppRunbooksIdRouteImport } from './routes/_app.runbooks.$id'
import { Route as AppKnowledgeBaseProjectIdRouteImport } from './routes/_app.knowledge-base.$projectId'
import { Route as AppInboxIdRouteImport } from './routes/_app.inbox.$id'
import { Route as AppKnowledgeBaseProjectIdIndexRouteImport } from './routes/_app.knowledge-base.$projectId.index'
import { Route as AppKnowledgeBaseProjectIdDocIdRouteImport } from './routes/_app.knowledge-base.$projectId.$docId'
import { Route as AppConnectionsCreateTypeRouteImport } from './routes/_app.connections.create.$type'
import { Route as AppConnectionsIdEditRouteImport } from './routes/_app.connections.$id.edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppRunbooksRoute = AppRunbooksRouteImport.update({
  id: '/runbooks',
  path: '/runbooks',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeBaseRoute = AppKnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentHistoryRoute = AppIncidentHistoryRouteImport.update({
  id: '/incident-history',
  path: '/incident-history',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppRunbooksIndexRoute = AppRunbooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRunbooksRoute,
} as any)
const AppKnowledgeBaseIndexRoute = AppKnowledgeBaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppKnowledgeBaseRoute,
} as any)
const AppInboxIndexRoute = AppInboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInboxRoute,
} as any)
const AppRunbooksIdRoute = AppRunbooksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppRunbooksRoute,
} as any)
const AppKnowledgeBaseProjectIdRoute =
  AppKnowledgeBaseProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AppKnowledgeBaseRoute,
  } as any)
const AppInboxIdRoute = AppInboxIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInboxRoute,
} as any)
const AppKnowledgeBaseProjectIdIndexRoute =
  AppKnowledgeBaseProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppKnowledgeBaseProjectIdRoute,
  } as any)
const AppKnowledgeBaseProjectIdDocIdRoute =
  AppKnowledgeBaseProjectIdDocIdRouteImport.update({
    id: '/$docId',
    path: '/$docId',
    getParentRoute: () => AppKnowledgeBaseProjectIdRoute,
  } as any)
const AppConnectionsCreateTypeRoute =
  AppConnectionsCreateTypeRouteImport.update({
    id: '/connections/create/$type',
    path: '/connections/create/$type',
    getParentRoute: () => AppRoute,
  } as any)
const AppConnectionsIdEditRoute = AppConnectionsIdEditRouteImport.update({
  id: '/connections/$id/edit',
  path: '/connections/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/inbox': typeof AppInboxRouteWithChildren
  '/incident-history': typeof AppIncidentHistoryRoute
  '/knowledge-base': typeof AppKnowledgeBaseRouteWithChildren
  '/projects': typeof AppProjectsRoute
  '/runbooks': typeof AppRunbooksRouteWithChildren
  '/services': typeof AppServicesRoute
  '/skills': typeof AppSkillsRoute
  '/inbox/$id': typeof AppInboxIdRoute
  '/knowledge-base/$projectId': typeof AppKnowledgeBaseProjectIdRouteWithChildren
  '/runbooks/$id': typeof AppRunbooksIdRoute
  '/inbox/': typeof AppInboxIndexRoute
  '/knowledge-base/': typeof AppKnowledgeBaseIndexRoute
  '/runbooks/': typeof AppRunbooksIndexRoute
  '/connections/$id/edit': typeof AppConnectionsIdEditRoute
  '/connections/create/$type': typeof AppConnectionsCreateTypeRoute
  '/knowledge-base/$projectId/$docId': typeof AppKnowledgeBaseProjectIdDocIdRoute
  '/knowledge-base/$projectId/': typeof AppKnowledgeBaseProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/incident-history': typeof AppIncidentHistoryRoute
  '/projects': typeof AppProjectsRoute
  '/services': typeof AppServicesRoute
  '/skills': typeof AppSkillsRoute
  '/': typeof AppIndexRoute
  '/inbox/$id': typeof AppInboxIdRoute
  '/runbooks/$id': typeof AppRunbooksIdRoute
  '/inbox': typeof AppInboxIndexRoute
  '/knowledge-base': typeof AppKnowledgeBaseIndexRoute
  '/runbooks': typeof AppRunbooksIndexRoute
  '/connections/$id/edit': typeof AppConnectionsIdEditRoute
  '/connections/create/$type': typeof AppConnectionsCreateTypeRoute
  '/knowledge-base/$projectId/$docId': typeof AppKnowledgeBaseProjectIdDocIdRoute
  '/knowledge-base/$projectId': typeof AppKnowledgeBaseProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/inbox': typeof AppInboxRouteWithChildren
  '/_app/incident-history': typeof AppIncidentHistoryRoute
  '/_app/knowledge-base': typeof AppKnowledgeBaseRouteWithChildren
  '/_app/projects': typeof AppProjectsRoute
  '/_app/runbooks': typeof AppRunbooksRouteWithChildren
  '/_app/services': typeof AppServicesRoute
  '/_app/skills': typeof AppSkillsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/inbox/$id': typeof AppInboxIdRoute
  '/_app/knowledge-base/$projectId': typeof AppKnowledgeBaseProjectIdRouteWithChildren
  '/_app/runbooks/$id': typeof AppRunbooksIdRoute
  '/_app/inbox/': typeof AppInboxIndexRoute
  '/_app/knowledge-base/': typeof AppKnowledgeBaseIndexRoute
  '/_app/runbooks/': typeof AppRunbooksIndexRoute
  '/_app/connections/$id/edit': typeof AppConnectionsIdEditRoute
  '/_app/connections/create/$type': typeof AppConnectionsCreateTypeRoute
  '/_app/knowledge-base/$projectId/$docId': typeof AppKnowledgeBaseProjectIdDocIdRoute
  '/_app/knowledge-base/$projectId/': typeof AppKnowledgeBaseProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inbox'
    | '/incident-history'
    | '/knowledge-base'
    | '/projects'
    | '/runbooks'
    | '/services'
    | '/skills'
    | '/inbox/$id'
    | '/knowledge-base/$projectId'
    | '/runbooks/$id'
    | '/inbox/'
    | '/knowledge-base/'
    | '/runbooks/'
    | '/connections/$id/edit'
    | '/connections/create/$type'
    | '/knowledge-base/$projectId/$docId'
    | '/knowledge-base/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/incident-history'
    | '/projects'
    | '/services'
    | '/skills'
    | '/'
    | '/inbox/$id'
    | '/runbooks/$id'
    | '/inbox'
    | '/knowledge-base'
    | '/runbooks'
    | '/connections/$id/edit'
    | '/connections/create/$type'
    | '/knowledge-base/$projectId/$docId'
    | '/knowledge-base/$projectId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/inbox'
    | '/_app/incident-history'
    | '/_app/knowledge-base'
    | '/_app/projects'
    | '/_app/runbooks'
    | '/_app/services'
    | '/_app/skills'
    | '/_app/'
    | '/_app/inbox/$id'
    | '/_app/knowledge-base/$projectId'
    | '/_app/runbooks/$id'
    | '/_app/inbox/'
    | '/_app/knowledge-base/'
    | '/_app/runbooks/'
    | '/_app/connections/$id/edit'
    | '/_app/connections/create/$type'
    | '/_app/knowledge-base/$projectId/$docId'
    | '/_app/knowledge-base/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services': {
      id: '/_app/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runbooks': {
      id: '/_app/runbooks'
      path: '/runbooks'
      fullPath: '/runbooks'
      preLoaderRoute: typeof AppRunbooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge-base': {
      id: '/_app/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof AppKnowledgeBaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incident-history': {
      id: '/_app/incident-history'
      path: '/incident-history'
      fullPath: '/incident-history'
      preLoaderRoute: typeof AppIncidentHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runbooks/': {
      id: '/_app/runbooks/'
      path: '/'
      fullPath: '/runbooks/'
      preLoaderRoute: typeof AppRunbooksIndexRouteImport
      parentRoute: typeof AppRunbooksRoute
    }
    '/_app/knowledge-base/': {
      id: '/_app/knowledge-base/'
      path: '/'
      fullPath: '/knowledge-base/'
      preLoaderRoute: typeof AppKnowledgeBaseIndexRouteImport
      parentRoute: typeof AppKnowledgeBaseRoute
    }
    '/_app/inbox/': {
      id: '/_app/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AppInboxIndexRouteImport
      parentRoute: typeof AppInboxRoute
    }
    '/_app/runbooks/$id': {
      id: '/_app/runbooks/$id'
      path: '/$id'
      fullPath: '/runbooks/$id'
      preLoaderRoute: typeof AppRunbooksIdRouteImport
      parentRoute: typeof AppRunbooksRoute
    }
    '/_app/knowledge-base/$projectId': {
      id: '/_app/knowledge-base/$projectId'
      path: '/$projectId'
      fullPath: '/knowledge-base/$projectId'
      preLoaderRoute: typeof AppKnowledgeBaseProjectIdRouteImport
      parentRoute: typeof AppKnowledgeBaseRoute
    }
    '/_app/inbox/$id': {
      id: '/_app/inbox/$id'
      path: '/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof AppInboxIdRouteImport
      parentRoute: typeof AppInboxRoute
    }
    '/_app/knowledge-base/$projectId/': {
      id: '/_app/knowledge-base/$projectId/'
      path: '/'
      fullPath: '/knowledge-base/$projectId/'
      preLoaderRoute: typeof AppKnowledgeBaseProjectIdIndexRouteImport
      parentRoute: typeof AppKnowledgeBaseProjectIdRoute
    }
    '/_app/knowledge-base/$projectId/$docId': {
      id: '/_app/knowledge-base/$projectId/$docId'
      path: '/$docId'
      fullPath: '/knowledge-base/$projectId/$docId'
      preLoaderRoute: typeof AppKnowledgeBaseProjectIdDocIdRouteImport
      parentRoute: typeof AppKnowledgeBaseProjectIdRoute
    }
    '/_app/connections/create/$type': {
      id: '/_app/connections/create/$type'
      path: '/connections/create/$type'
      fullPath: '/connections/create/$type'
      preLoaderRoute: typeof AppConnectionsCreateTypeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections/$id/edit': {
      id: '/_app/connections/$id/edit'
      path: '/connections/$id/edit'
      fullPath: '/connections/$id/edit'
      preLoaderRoute: typeof AppConnectionsIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppInboxRouteChildren {
  AppInboxIdRoute: typeof AppInboxIdRoute
  AppInboxIndexRoute: typeof AppInboxIndexRoute
}

const AppInboxRouteChildren: AppInboxRouteChildren = {
  AppInboxIdRoute: AppInboxIdRoute,
  AppInboxIndexRoute: AppInboxIndexRoute,
}

const AppInboxRouteWithChildren = AppInboxRoute._addFileChildren(
  AppInboxRouteChildren,
)

interface AppKnowledgeBaseProjectIdRouteChildren {
  AppKnowledgeBaseProjectIdDocIdRoute: typeof AppKnowledgeBaseProjectIdDocIdRoute
  AppKnowledgeBaseProjectIdIndexRoute: typeof AppKnowledgeBaseProjectIdIndexRoute
}

const AppKnowledgeBaseProjectIdRouteChildren: AppKnowledgeBaseProjectIdRouteChildren =
  {
    AppKnowledgeBaseProjectIdDocIdRoute: AppKnowledgeBaseProjectIdDocIdRoute,
    AppKnowledgeBaseProjectIdIndexRoute: AppKnowledgeBaseProjectIdIndexRoute,
  }

const AppKnowledgeBaseProjectIdRouteWithChildren =
  AppKnowledgeBaseProjectIdRoute._addFileChildren(
    AppKnowledgeBaseProjectIdRouteChildren,
  )

interface AppKnowledgeBaseRouteChildren {
  AppKnowledgeBaseProjectIdRoute: typeof AppKnowledgeBaseProjectIdRouteWithChildren
  AppKnowledgeBaseIndexRoute: typeof AppKnowledgeBaseIndexRoute
}

const AppKnowledgeBaseRouteChildren: AppKnowledgeBaseRouteChildren = {
  AppKnowledgeBaseProjectIdRoute: AppKnowledgeBaseProjectIdRouteWithChildren,
  AppKnowledgeBaseIndexRoute: AppKnowledgeBaseIndexRoute,
}

const AppKnowledgeBaseRouteWithChildren =
  AppKnowledgeBaseRoute._addFileChildren(AppKnowledgeBaseRouteChildren)

interface AppRunbooksRouteChildren {
  AppRunbooksIdRoute: typeof AppRunbooksIdRoute
  AppRunbooksIndexRoute: typeof AppRunbooksIndexRoute
}

const AppRunbooksRouteChildren: AppRunbooksRouteChildren = {
  AppRunbooksIdRoute: AppRunbooksIdRoute,
  AppRunbooksIndexRoute: AppRunbooksIndexRoute,
}

const AppRunbooksRouteWithChildren = AppRunbooksRoute._addFileChildren(
  AppRunbooksRouteChildren,
)

interface AppRouteChildren {
  AppInboxRoute: typeof AppInboxRouteWithChildren
  AppIncidentHistoryRoute: typeof AppIncidentHistoryRoute
  AppKnowledgeBaseRoute: typeof AppKnowledgeBaseRouteWithChildren
  AppProjectsRoute: typeof AppProjectsRoute
  AppRunbooksRoute: typeof AppRunbooksRouteWithChildren
  AppServicesRoute: typeof AppServicesRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppConnectionsIdEditRoute: typeof AppConnectionsIdEditRoute
  AppConnectionsCreateTypeRoute: typeof AppConnectionsCreateTypeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInboxRoute: AppInboxRouteWithChildren,
  AppIncidentHistoryRoute: AppIncidentHistoryRoute,
  AppKnowledgeBaseRoute: AppKnowledgeBaseRouteWithChildren,
  AppProjectsRoute: AppProjectsRoute,
  AppRunbooksRoute: AppRunbooksRouteWithChildren,
  AppServicesRoute: AppServicesRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppIndexRoute: AppIndexRoute,
  AppConnectionsIdEditRoute: AppConnectionsIdEditRoute,
  AppConnectionsCreateTypeRoute: AppConnectionsCreateTypeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
